### ISSUE TITLE
Update documentation for initial tft flash

### ISSUE THREAD

**Issue by Grrzzz** [olicooper/esphome-nspanel-lovelace-native#13]
The service upload_tft will fail with basic configuration example because the display is turned off. Took me hours to get behind this issue.
Please update your documentation and add screen power to basic example (https://github.com/olicooper/esphome-nspanel-lovelace-native/blob/dev/basic-example.yaml#L80)

> switch:
  ## Turn screen power on/off
  - platform: gpio
    name: Screen Power
    id: screen_power
    entity_category: config
    pin:
      number: 4
      inverted: true
    restore_mode: ALWAYS_ON

**Comment by olicooper** [comment]
Sorry about that, I tried to simplify the config but I also removed this required entry in the process! Thanks for reporting it 👍
