### ISSUE TITLE
Not an issue, just a note to say "Thank You"

### ISSUE THREAD

**Issue by CultusMechanicus** [olicooper/esphome-nspanel-lovelace-native#17]
Thanks for the effort that has gone into this, the recent addition of CardThermo has completed the set of controls I used with the old AppDaemon backend. This project is much slicker and faster, and it's easier to maintain the UI in esphome configs as well.

Thanks again for all your effort!

**Comment by olicooper** [comment]
That's very kind, glad it is working well for you!

**Comment by nstrelow** [comment]
Want to +1 the whole project. It's so much faster, it feels so much more usable. 

Just had my first install and will now migrate my config.

So thanks a lot for building this cool project 
😁
