### ISSUE TITLE
EU-Variant: Rotate Device

### ISSUE THREAD

**Issue by newhinton** [olicooper/esphome-nspanel-lovelace-native#19]
Hi!

The european version is usually landscape. Would it be possible to rotate the device, so that the buttons are on the side of the device? Is that impossible, or does this belong into the "upstream"-repository?

**Comment by olicooper** [comment]
Hi, yes this is an upstream issue. The graphics display is handled by the [HMI firmware](https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI), this repo just handles the communication between the display and Home Assistant. You'd have to open a ticket with the upstream repo for that functionality 👍
