### ISSUE TITLE
Alarm Card can't use PIN code to disarm

### ISSUE THREAD

**Issue by paulbyrne-spacenk** [olicooper/esphome-nspanel-lovelace-native#5]
The alarm card works to arm and disarm the alarm, however it doesn't show the number pad when disarming and can't disarm alarms that require a code. e.g. an Alarmo alarm with 'Require code for disarming' set can't be disarmed.

**Comment by paulbyrne-spacenk** [comment]
Oh, I see what it's doing! Not sure if this is a bug here or with Alarmo actually. Nspanel checks  code_arm_required, which is only set to true in Alarmo if you require arming codes, not just disarming codes. Either way, I can work with that. Closing this one.

**Comment by CultusMechanicus** [comment]
For anyone who has this issue and is using the Alarmo integration, here's how to fix it:-
Under 'Codes' in Alarmo  there's three toggles, called "Require code for 'x'". Turn them all on.
Make sure all your user codes are set to both "Allow for Arm" and "Allow for Disarm".
The nspanel will now show the keypad where you need it.
